title: Sen's world
author: Senmao ji
email: Senmao.ji@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Workbench for my proyects
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
